swuecho/chat

api/chat_main_service.go
api/chat_message_handler.go
api/chat_prompt_service.go
api/go.mod
api/go.sum
api/sqlc/queries/chat_message.sql
api/sqlc/queries/chat_prompt.sql
api/sqlc/schema.sql
api/sqlc_queries/chat_message.sql.go
api/sqlc_queries/chat_prompt.sql.go
api/sqlc_queries/models.go
api/util.go

token count

---

web/src/views/chat/components/Message/Text.vue

https://github.com/Chanzhaoyu/chatgpt-web/pull/1492

 markdown 表格内没有换行

---

web/package.json
web/pnpm-lock.yaml
web/src/components/common/Setting/General.vue
web/src/components/common/Setting/index.vue
web/src/components/common/UserAvatar/index.vue
web/src/locales/zh-CN.json
web/src/store/modules/user/helper.ts
web/src/utils/jwt.ts
web/src/views/snapshot/components/Header/index.vue

https://github.com/swuecho/chat/issues/136

isAdminUser

---

.github/workflows/docker-image.yml
api/chat_main_handler.go
api/chat_message_service.go
api/models.go
api/sqlc/queries/chat_model.sql
api/sqlc/schema.sql
api/sqlc_queries/chat_model.sql.go
api/sqlc_queries/models.go
web/src/api/index.ts
web/src/typings/chat.d.ts
web/src/views/chat/index.vue
web/src/views/snapshot/index.vue

```js
export async function handleEcho(request: Request): Promise<Response> {
// Set up an SSE stream
const { prompt, model }: { prompt: string, model: string } = await request.json()
// \n\nHuman: %s\n\nAssistant: 
// trim last line
const split_by_humam = prompt.split('\n\nHuman:')
const last_human = split_by_humam[split_by_humam.length - 1]
const echo_response = last_human.split('\n\nAssistant:')[0]
const completion = JSON.stringify(
{
Completion: echo_response,
Model: model
}
)
const ab = new TextEncoder().encode(`data: ${completion}\n\n`)
const stream = new ReadableStream({
start(controller) {
controller.enqueue(ab)
// End the stream
controller.close()
}
})
// Return the SSE stream as the response
return new Response(stream, {
headers: {
'Content-Type': 'text/event-stream', …
```

Add custom echo model

---

api/chat_message_service.go
api/models.go
web/src/api/index.ts
web/src/typings/chat.d.ts
web/src/views/chat/index.vue
web/src/views/snapshot/index.vue

https://github.com/swuecho/chat/issues/137

remote extra fields

---

web/package.json
web/pnpm-lock.yaml

"typescript": "4.9.5" root cause

lock vue vue-router typescript  version

---

api/chat_main_handler.go
api/text_buffer.go
web/src/locales/zh-CN.json
web/src/views/chat/components/Session/SessionConfig.vue
web/src/views/components/Message/Text.vue

text davinci 003 generate N completions at the same time

---

api/sqlc/queries/chat_message.sql
api/sqlc_queries/chat_message.sql.go

feat(chat-message): always send is_pin message

---

README.md

style: bit misspell README

---

api/chat_auth_user_handler.go
api/chat_model_privilege_handler.go
api/chat_user_active_chat_sesion_handler.go

10years_token

---

web/src/utils/date.ts

Revert "fix_format_in_ios"

---

api/sqlc/schema.sql
web/src/views/chat/components/Session/SessionConfig.vue

gpt 16k support

---

web/src/views/chat/index.vue

set loading value to false on error

---

api/chat_main_handler.go

1. download ollama and pull mistral model.
3. config ollama model in chat model 
id: ollama-{modelName}
baseUrl: http://hostname:11434/api/generate

basic ollama support

---

api/chat_main_handler.go
api/ollama.go

https://colab.research.google.com/drive/14KvD_bMnXwLBqeKwaNZoWW4RqWt5kVBA?usp=sharing#scrollTo=Tcukqu1d2BKX

ollama-neural-chat

---

api/handle_tts.go
api/main.go
api/middleware_authenticate.go
web/src/locales/zh-CN.json
web/src/views/chat/components/AudioPlayer/index.vue
web/src/views/chat/components/Message/index.vue
web/src/views/chat/index.vue

Assuming you have a coqui tts server running
https://tts.readthedocs.io/en/latest/installation.html
provide the coqui tts running host and port an env var
export TTS_HOST=192.168.0.14
export TTS_PORT=5002

basic audio support (coqui)

---

web/src/views/components/Permission.vue

fix error in signup

---

web/src/views/chat/layout/sider/List.vue

update handleSyncChat in List.vue

---

web/src/components/common/Setting/General.vue
web/src/components/common/UserAvatar/index.vue
web/src/locales/en-US.json
web/src/locales/zh-CN.json
web/src/locales/zh-TW.json
web/src/views/chat/components/AudioPlayer/index.vue
web/src/views/chat/components/Message/index.vue
web/src/views/chat/index.vue

修改信息布局
修改语音图标及布局，固定在头像周围
添加默认名称和描述

Update message layout, audiobtn icon and add default name/desc

---

web/src/views/admin/model/AddModelForm.vue
web/src/views/admin/model/index.vue
web/src/views/admin/modelRateLimit/index.vue

Revert "query model"

---

api/chat_main_handler.go
api/chat_snapshot_handler.go
api/sqlc/queries/chat_snapshot.sql
api/sqlc_queries/chat_snapshot.sql.go
scripts/auto_commit.py
web/src/api/chat_main.ts
web/src/views/chat/components/Message/index.vue

- Increased timeout in auto_commit.py for API requests.
- Renamed OpenAIChatCompletionAPIWithStreamHandler to ChatCompletionHandler.
- Added ChatBotCompletionHandler for bot functionality.
- Updated SQL queries to include ChatSnapshotByUserIdAndUuid.
- Improved error handling and logging in ChatCompletionHandler.
- Fixed proxy variable name in auto_commit.py.

Refactor API handlers and improve auto_commit script

---

api/chat_main_handler.go
api/llm_openai.go

- Added OpenRouter API URL handling in `llm_openai.go`.
- Enhanced logging in `chat_main_handler.go` for better debugging:
- Added detailed config logging.
- Added pre-request and stream error logging.

Add OpenRouter support and improve logging in chat handler

---

responsive-fixes-summary.md
web/src/views/chat/components/Message/ArtifactViewer.vue
web/src/views/chat/components/Message/index.vue
web/src/views/components/Message/style.less

Improve responsiveness of the message display and artifact viewer on mobile devices.

Fix unresponsive message display

---

api/chat_main_service.go
artifacts.md
code_runner.md
web/public/workers/jsRunner.js
web/src/services/codeRunner.ts
web/src/typings/chat.d.ts
web/src/views/chat/components/Message/ArtifactViewer.vue

This message:
- Summarizes the main feature being added (code runner)
- Mentions key aspects (JS execution, artifact support)
- Is concise (<50 chars for title)
- Reflects the substantial additions shown in the diff stats

"Add code runner feature with JS execution and artifact support"

---

web/src/views/chat/components/Conversation.vue

The changes:
- Split large `onRegenerate` function into smaller focused functions
- Improved code organization and readability
- Maintained same functionality while making logic clearer
- Added proper error handling and validation

Refactor regenerate chat logic into smaller functions

---

test_vfs_upload.csv
web/public/workers/jsRunner.js
web/public/workers/pyRunner.js
web/src/components/ChatVFSUploader.vue
web/src/components/VFSProvider.vue
web/src/services/codeRunner.ts
web/src/utils/virtualFileSystem.js

- Implemented JS and Python worker runners
- Enhanced VFS with upload capability
- Added code runner service integration
- Updated VFS provider component

Added code runners and VFS support for web IDE

---

api/artifact_instruction.txt
api/chat_artifact.go
web/src/views/chat/components/Conversation.vue
web/src/views/chat/components/Message/ArtifactViewer.vue
web/src/views/chat/composables/useStreamHandling.ts

- Update HTML artifact guidelines to recommend Preact over vanilla JS
- Improve scrollbar styling across chat UI components
- Fix mobile layout and spacing in Conversation view
- Enhance error handling in stream handling logic
- Add consistent scrollbar styling for dark mode

Update artifact guidelines and UI improvements

---

web/src/views/chat/components/Message/index.vue
web/src/views/chat/components/MessageList.vue
web/src/views/chat/composables/useConversationFlow.ts
web/src/views/chat/composables/useStreamHandling.ts

- Added `suggestedQuestionsLoading` prop to Message component
- Updated MessageList to pass loading state
- Set loading state when starting conversation in explore mode
- Clear loading state when suggested questions are received
- Improved suggested questions loading logic in Message component

Add loading state for suggested questions in explore mode
